---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/local/apps/monitoring
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
