apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
resources:
  - grafana/kustomization.yaml
  - prometheus/kustomization.yaml
  - promtail/kustomization.yaml
  - loki/kustomization.yaml
