apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
spec:
  interval: 1m
  path: "./clusters/local/apps/monitoring"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
