apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mysql
  namespace: flux-system
resources:
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-secret.sops.yaml
