apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx
spec:
  interval: 5m
  path: "./apps/ingress-nginx"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
