apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: wordpress
  namespace: flux-system
resources:
  - wordpress-deployment.yaml
  - wordpress-service.yaml
  - ingress.yaml
