apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters/local/apps/metallb"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
