apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: 6.17.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    adminUser: admin
    adminPassword: admin
