apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.17.4
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    adminUser: admin
    adminPassword: admin
